import { NextPage } from "next";
import Head from "next/head";

const About: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>KFUPM Computer Club | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default About;
