import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ReactNode } from "react";
import HeroCard from "../components/HeroCard";

const Home: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>KFUPM Computer Club | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-5" />
      <HeroCard
        href="/about"
        src="/images/blueMan.svg"
        title="حيث تلتقي التقنية بالعلم"
        subtitle="نادينا يوصلك لآخر أخبار التقنية اللي وصل لها العالم"
        linkTitle="ودك تعرف أكثر؟"
        dir="ltr"
      />
      <HeroCard
        href="/about"
        src="/images/blueMan2.svg"
        title="إبداعنا ماله حدود"
        subtitle="انضم اليوم الى نادي الحاسب في جامعة الملك فهد"
        linkTitle="حاب تورينا ابداعك؟"
      />
      <HeroCard
        href="/about"
        src="/images/woman.svg"
        title="تواصل معنا ونرد بسرعة البرق"
        subtitle="نقدم لك استشارات تقنية لمشروعك أو اعمالك اللي تحتاجنا فيها"
        linkTitle="تعاون معنا الآن"
        dir="ltr"
      />
    </>
  );
};

export default Home;
